KNOWN_SKILLS = {
    "python": "Python",
    "fastapi": "FastAPI",
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "typescript": "TypeScript",
    "javascript": "JavaScript",
    "react": "React",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "nestjs": "NestJS",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "prisma": "Prisma",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "aws": "AWS",
    "redis": "Redis",
    "openai": "OpenAI",
    "langchain": "LangChain",
    "llm": "LLM",
    "rag": "RAG",
    "pgvector": "pgvector",
    "vector search": "Vector Search",
    "embeddings": "Embeddings",
    "prompt versioning": "Prompt Versioning",
    "evaluation": "Evaluation",
    "observability": "Observability",
    "openai apis": "LLM",
    "openai api": "LLM",
    "llm api": "LLM",
    "llm apis": "LLM",

    "prompt engineering": "Prompt Engineering",
    "prompt engineer": "Prompt Engineering",

    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",

    "ts": "TypeScript",

    "containerized services": "Docker",
    "containerized applications": "Docker",
    "containers": "Docker",
}